# Generated by Django 3.2.5 on 2021-07-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetails',
            old_name='bok',
            new_name='book',
        ),
    ]
